{******************************************************************************}
{                                                                              }
{                         Local Compiler Directives                            }
{                                                                              }
{  Данный включаемый файл содержит локальные директивы компилятора.            }
{                                                                              }
{                       Copyright © 2010 by Xcentric                           }
{                                                                              }
{******************************************************************************}

{$ALIGN 8}  // Default {$ALIGN 8}
{$ASSERTIONS ON}  // Default {$ASSERTIONS ON}
{$BOOLEVAL OFF}  // Default {$BOOLEVAL OFF}
{$HIGHCHARUNICODE OFF}  // Default {$HIGHCHARUNICODE OFF}
{$HINTS ON}  // Default {$HINTS ON}
{$IMPORTEDDATA ON}  // Default {$IMPORTEDDATA ON}
{$IOCHECKS ON}  // Default {$IOCHECKS ON}
{$LONGSTRINGS ON}  // Default {$LONGSTRINGS ON}
{$METHODINFO OFF}  // Default {$METHODINFO OFF}
{$MINENUMSIZE 1}  // Default {$MINENUMSIZE 1}
{$OPENSTRINGS ON}  // Default {$OPENSTRINGS ON}
{$OPTIMIZATION ON}  // Default {$OPTIMIZATION ON}
{$OVERFLOWCHECKS OFF}  // Default {$OVERFLOWCHECKS OFF}
{$SAFEDIVIDE OFF}  // Default {$SAFEDIVIDE OFF}
{$POINTERMATH OFF}  // Default {$POINTERMATH OFF}
{$RANGECHECKS OFF}  // Default {$RANGECHECKS OFF}
{$REALCOMPATIBILITY OFF}  // Default {$REALCOMPATIBILITY OFF}

{.$RTTI EXPLICIT METHODS([vcPrivate, vcProtected, vcPublic, vcPublished])
                PROPERTIES([vcPrivate, vcProtected, vcPublic, vcPublished])
				FIELDS([vcPrivate, vcProtected, vcPublic, vcPublished])}
// Default:
//{$RTTI EXPLICIT METHODS([vcPublic, vcPublished])
//                PROPERTIES([vcPublic, vcPublished])
//                FIELDS([vcPrivate, vcProtected, vcPublic, vcPublished])}

{$TYPEINFO OFF}  // Default {$TYPEINFO OFF}
{$SCOPEDENUMS OFF}  // Default {$SCOPEDENUMS OFF}
{$STACKFRAMES OFF}  // Default {$STACKFRAMES OFF}
{$VARSTRINGCHECKS ON}  // Default {$VARSTRINGCHECKS ON}

{.$WARN SYMBOL_PLATFORM OFF}  // Default {$WARN SYMBOL_PLATFORM ON}
{$WARN SYMBOL_LIBRARY ON}  // Default {$WARN SYMBOL_LIBRARY ON}
{$WARN SYMBOL_DEPRECATED ON}  // Default {$WARN SYMBOL_DEPRECATED ON}
{$WARN UNIT_DEPRECATED ON}  // Default {$WARN UNIT_DEPRECATED ON}
{$WARN UNIT_LIBRARY ON}  // Default {$WARN UNIT_LIBRARY ON}
{$WARN UNIT_PLATFORM ON}  // Default {$WARN UNIT_PLATFORM ON}

{$WARNINGS ON}  // Default {$WARNINGS ON}
{$WEAKPACKAGEUNIT OFF}  // Default {$WEAKPACKAGEUNIT OFF}
{$WEAKLINKRTTI OFF}  // Default {$WEAKLINKRTTI OFF}
{$WRITEABLECONST OFF}  // Default {$WRITEABLECONST OFF}