CREATE SCHEMA IF NOT EXISTS `main` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE SCHEMA IF NOT EXISTS `hardware_config` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE SCHEMA IF NOT EXISTS `software_config` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;